version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: BD
    ports:
      - '3306:3306'
    volumes:
      - ./respaldotel:/var/lib/mysql
      
  app:
    build: .
    ports:
<<<<<<< HEAD
      - '3000:3000'
=======
      - '3010:3000'
>>>>>>> bdf384fc683bd845b3525d02ddf2f4b6ba0b53e4
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: BD
<<<<<<< HEAD
=======

>>>>>>> bdf384fc683bd845b3525d02ddf2f4b6ba0b53e4

