version: '3.8'

services:
  db:
    image: mysql:8.0.35
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: BD
    volumes:
      - ./respaldotel:/var/lib/mysql
      - ./BD.sql:/docker-entrypoint-initdb.d/BD.sql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mitel
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: admin
      DB_DATABASE: BD
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
